### ISSUE TITLE
Versioning schema question

### ISSUE THREAD

**Issue by mensfeld** [kaizhu256/v8-coverage-report#1]
Hey, just a quick question: what versioning schema are you planning to use? I noticed you started with 1000.x and went to a date based one. Is the date based one going to be the new one?

Thank you for this lib.

**Comment by kaizhu256** [comment]
the 1000x was in anticipation that mistakes might be made while setting up the automated npm-publish ci (its my first attempt doing it), and don't want to waste real-dates on test-runs to npm-publish.  but yea, the real versioning is date-based, once i felt the kinks were worked out in the ci ^_^

**Comment by mensfeld** [comment]
Thank you for the explanation. Have a nice day :)

**Comment by kaizhu256** [comment]
you too, and good to know it helps!
